spring:
  application:
          name: InstaClone
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/InstaCloneRealm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
server:
  port: 8081
jwt:
  auth:
    converter:
      resource-id: InstaClone_api_demo
      principale-attribute: preferred_username